### ISSUE TITLE
1.1.4版本获取不到用户信息，即使显示也是一片空白

### ISSUE THREAD

**Issue by Arcadia7** [leck995/WutheringWavesTool#12]
这是进入“主页”的状态，会一闪而过，然后空白
![I1}VB}D05TUGCVX7Z_K_{(I](https://github.com/user-attachments/assets/c18ccb97-536d-4349-9261-1b833bc5f183)
多次进入有可能能够成功加载出
![~_UL538C86%3O6Q6L$PBMV8](https://github.com/user-attachments/assets/658787b9-d767-44c6-8e7c-128a5bda3fb2)
但是只有体力是获取成功的

另外再提一个ui的建议，从设计上来说
![image](https://github.com/user-attachments/assets/b665482b-d8d5-44db-941a-9975e8c55c76)
这个不该叫菜单，应该叫展开/收起，这不是一个有效的页面，只是一个对侧边内容的css动态变化的功能

**Comment by leck995** [comment]
是最新版的吗，因为我在数小时前曾进行一次更新，应该修复了因Api变化导致的部分数据无法获取的问题，目前我以再次更新了一次。
至于菜单，两种说法都可以，只是理解角度不一样；一种站在该按钮的功能上来解释，一种站在侧边栏的意义上来解释。

**Comment by Arcadia7** [comment]
使用最新的v3版本确实是没有问题了

**Comment by MilchstraBe-Z** [comment]
想问作者v4版本是不是又出现这个问题了呀，我现在也是有这个问题
![Uploading java_7cyXYWBglZ.jpg…]()
