### ISSUE TITLE
1.1.4-pre3版本 “隐藏至托盘”会导致软件直接关闭

### ISSUE THREAD

**Issue by DogeKang** [leck995/WutheringWavesTool#13]
手动点x后选择“隐藏至托盘”，程序会直接关闭；
在设置里勾选“游戏启动时隐藏程序至托盘”后，启动游戏，程序会直接关闭，而非隐藏至托盘。
这个现象独在1.1.4各个版本出现，1.1.3未出现该现象。
尝试过从1.1.3版本直接覆盖升级到1.1.4，还是删除旧版本内容重新解压1.1.4，该现象依旧存在。

**Comment by leck995** [comment]
已修复
