### ISSUE TITLE
根据token获取信息不全，偶尔出现无法加载信息

### ISSUE THREAD

**Issue by MilchstraBe-Z** [leck995/WutheringWavesTool#14]
参考#12 出现类似的问题
情况：首页概率加载出体力信息，自动签到功能失败，角色失败，游戏时长统计的账号名不一致。
报错均为：
Failed to convert property value of type
'java.lang. String' to required type 'java.lang. Long'for property 'roleld'; nested exception is
java.lang.NumberFormatExce ption: For input string: "Kurokawa"
注："Kurokawa"是我输入的游戏ID

只有体力加载（图一）；完全无信息（图二）
![image](https://github.com/user-attachments/assets/f2c23e38-f0f0-4c96-b1f9-b06420d4a0d9)
![image](https://github.com/user-attachments/assets/f6371c98-b3eb-4e24-9c1c-a910dd0c6317)

**Comment by leck995** [comment]
账号信息填写错了，游戏ID是又叫特征码，是游戏右下角的一串数字，而非游戏昵称或者其他。

**Comment by MilchstraBe-Z** [comment]
哦这，太尴尬了，试了下没问题了
