### ISSUE TITLE
希望启动游戏能加一个从steam中启动的方式

### ISSUE THREAD

**Issue by B1ngFeng** [leck995/WutheringWavesTool#15]
因为steam截图比较方便，所以我把鸣潮添加到了steam，每次从steam启动。
又想统计游戏时长，所以又需要用本工具启动。
所以想问能不能在设置里给“启动游戏”加一个从steam启动的选项，从URL启动就行，steam的URL格式是“steam://rungameid/xxxxx”，在steam添加第三方游戏之后，添加桌面快捷方式，然后查看快捷方式的详情，就能看到这个，让用户自己填一下，这样就既可以通过本工具统计时长，又可以用steam的截图功能。
或者有什么好用的截图方法吗，一个键截图并且不带光标，而且文件大小不要太大。

**Comment by B1ngFeng** [comment]
以及，我是从wegame安装的，设置好安装目录之后，启动游戏提示找不到，因为wegame的安装目录下直接就是.exe，不用再进wuthering waves game的文件夹

**Comment by leck995** [comment]
项目有实现截图功能的计划，但并不是最优先级的，可能需要一段时间。
如果仅仅是为了截图而使用steam，倒也没必要，win自带的截图也很不错，或者使用其他截图软件，这类软件市面上很多，如我常用picpick来进行截图。

我没有下载wegame版的，如果可以的话，请在此讨论中上传wegame版的文件层级截图，我将以此为依据适配wegame版。

**Comment by B1ngFeng** [comment]
设置里的安装目录是“D:\Game\WeGameApps\rail_apps\Wuthering Waves(2002137)”，Wuthering Waves.exe就在这个目录下，Client-Win64-Shipping.exe在“D:\Game\WeGameApps\rail_apps\Wuthering Waves(2002137)\Client\Binaries\Win64”。

我自己曲线救国成功了，在目录下自己建了一个Wuthering Waves Game文件夹，把steam创建快捷方式的url文件放里面，文件名是Wuthering Waves.url，然后自己C++写了个代码来启动这个url，编译成Wuthering Waves.exe，启动咱这个助手的时候用管理员权限，然后就可以用咱这个助手启动游戏了，代码如下：
```
#include <windows.h>

int main() {
    // Steam 游戏 URL
    const char* steamUrl = "steam://rungameid/15357160624970792960";

    // 使用 ShellExecuteEx 打开 URL
    SHELLEXECUTEINFO sei = { sizeof(sei) };
    sei.lpVerb = "open";
    sei.lpFile = steamUrl;
    sei.nShow = SW_SHOWNORMAL;

    if (!ShellExecuteEx(&sei)) {
        MessageBox(NULL, "Failed to open the Steam URL.", "Error", MB_OK | MB_ICONERROR);
    }

    return 0;
}
```

**Comment by B1ngFeng** [comment]
哦，还有个问题是抽卡分析一直提示我到抽卡分析界面去，但我到哪个界面都不行，看实际代码`File file=new File(Config.setting.getGameRootDir()+File.separator+"Wuthering Waves Game/Client/Saved/Logs/Client.log");`，应该也是目录不一样的问题，wegame的不用再进Wuthering Waves Game文件夹

**Comment by B1ngFeng** [comment]
对于抽卡分析，我又曲线救国，给文件夹建了个链接：
`D:\Game\WeGameApps\rail_apps>mklink /D "Wuthering Waves" "Wuthering Waves(2002137)"`
然后在助手的设置里把目录改成“D:\Game\WeGameApps\rail_apps”，然后能获取和刷新抽卡分析了，但是没有任何数据显示，这是为什么啊

**Comment by B1ngFeng** [comment]
我看我的Client.log里有一行（个人信息都换成xxx了）：
```
[2024.08.16-00.58.13:629][195][GameThread]Puerts: Display: (0x00000000525286D0) [5372][I][KuroSdk][YZY][26282][0.58.13:629] OpenWebView [sdkJson: {"title":"","url":"https://aki-gm-resources.aki-game.com/aki/gacha/index.html#/record?svr_id=xxxxxxxxxxxxxxxxxx&player_id=xxxxxxxxxxxxxx&lang=zh-Hans&gacha_id=4&gacha_type=6&svr_area=cn&record_id=xxxxxxxxxxxxxxxxxxxxx&resources_id=xxxxxxxxxxxxxxxxxxxxxxx","transparent":true,"titlebar":false,"innerbrowser":true,"webAccelerated":true}]
```
没仔细看，不知道程序是什么情况

**Comment by leck995** [comment]
很强的动手能力![177F2AA1](https://github.com/user-attachments/assets/73cb6739-da20-42d0-8092-2ffb5cb76009)

看起来抽卡没什么异常，我得下载wegame版测试一下，
我会在周末完成适配wegame版

**Comment by leck995** [comment]
我已经适配了WeGame。由于WeGame的解绑流程相当繁琐，加上我只有一个账号，因此我没有进行测试，所以无法确定它是否能够正常运行。
