### ISSUE TITLE
首页无法获取玩家角色信息和库街区信息

### ISSUE THREAD

**Issue by Realmajia** [leck995/WutheringWavesTool#17]
rt。今天打开首页显示错误提示业务异常，尝试删除账号数据，在浏览器重登陆kurobbs后用新cookie的token再次加入账号依然显示该错误。
![图片](https://github.com/user-attachments/assets/2e96afd7-80c7-449a-afb1-3c01776a349c)

**Comment by leck995** [comment]
库洛把部分接口改了，麻烦的是上了加密，暂时没研究出来如何解密

**Comment by Realmajia** [comment]
库洛太狗吧无聊了。。。。

**Comment by leck995** [comment]
已修复，下载最新版本即可
