### ISSUE TITLE
國際服問題

### ISSUE THREAD

**Issue by tony3071** [leck995/WutheringWavesTool#21]
好像要綁定庫街區才能統計時長
![image](https://github.com/user-attachments/assets/26277b32-789b-442b-8371-b0586a6b4483)

繁體的限定判定和頭像讀取有點問題
![image](https://github.com/user-attachments/assets/dbbab2e9-3c68-42c5-a7f8-95ed8a6aec99)

**Comment by tony3071** [comment]
補一下 武器也是一樣
![image](https://github.com/user-attachments/assets/a4d40e7c-ca82-40c3-8dae-5a7a6852b318)

**Comment by leck995** [comment]
已修复，游玩时长可能不支持繁体，不确定
