### ISSUE TITLE
添加账号时点击保存无响应

### ISSUE THREAD

**Issue by xyexep** [leck995/WutheringWavesTool#24]
![image](https://github.com/user-attachments/assets/c721fcf9-366b-43ec-9364-21d7b0591fb3)
输入两个id和token后点击保存没有反应，是否勾选设为主账号不影响

**Comment by xyexep** [comment]
win11系统

**Comment by leck995** [comment]
可尝试先使用库街区APP查看鸣潮相关数据后再进行添加
