### ISSUE TITLE
windows 防火墙会自动删除app.exe

### ISSUE THREAD

**Issue by 202211150054** [leck995/WutheringWavesTool#29]
我的系统为windows11，使用火绒防护，通常在1-2天后会自动扫描判定为严重威胁。(app.exe更名为wuwatool.exe)
![图片](https://github.com/user-attachments/assets/5b55a740-a025-4f2c-96d6-3bf8ae6d982b)
已经在火绒的信任区添加了所在目录。

**Comment by leck995** [comment]
误报属于常事，此问题应该向火绒反馈，我只能保证我发布的项目是没有病毒的。当然你可以尝试下载最新的v2版，该版本更换了打包方式
