### ISSUE TITLE
刷新抽卡分析不生效

### ISSUE THREAD

**Issue by Arcadia7** [leck995/WutheringWavesTool#3]
![image](https://github.com/leck995/WutheringWavesTool/assets/61370718/6a547425-68b7-46c2-b33e-e0bfdf3ab3e5)
会一直处于空白状态
如果将data文件下的文件删除 重新进行获取是能够正常获取到新的抽卡信息

**Comment by leck995** [comment]
模拟了多种情况，一切正常，我无法复现该问题。刷新前抽了哪些卡池，十连还是单抽，有什么值得注意的地方吗？如果再次出现该情况，可以保留一下date目录再联系我。

**Comment by Arcadia7** [comment]
近期在抽取武器池 全部是十连 
![5IVW`9I XAGGC4KQ3L6K6%M](https://github.com/leck995/WutheringWavesTool/assets/61370718/529a8c6a-d6dd-4700-bc57-bc15ee0e82a4)
这是常驻武器池 我的记录有14页*5=70抽 分析显示仍然是60抽
![ZVOG7U7H GVX{ M0U3$XOP5](https://github.com/leck995/WutheringWavesTool/assets/61370718/d64b7c0e-b349-4a4c-abfa-5d7312646c26)
这是限定武器池 具体同上 一样也是70抽 分析是50抽 刷新是不成功的
[刷新失败Data.zip](https://github.com/user-attachments/files/16171140/Data.zip)
[重新获取后的Data.zip](https://github.com/user-attachments/files/16171147/Data.zip)
同时，在我重新获取后，点击刷新会出现
![image](https://github.com/leck995/WutheringWavesTool/assets/61370718/bf9938e6-0a40-4f82-9489-1349c6723312)
