### ISSUE TITLE
被 Windows Defender 误判为病毒

### ISSUE THREAD

**Issue by rouVling** [leck995/WutheringWavesTool#30]
如图所示
![image](https://github.com/user-attachments/assets/335d65ef-8980-439e-977f-7e5188132986)

**Comment by huzhiyuan1994** [comment]
还有这个问题，最近每次都提醒
![image](https://github.com/user-attachments/assets/229ee577-b624-4a40-a008-15577c40dcc5)

**Comment by leck995** [comment]
windows自带防护报毒对于开源项目是家常便饭（你这个问题，氪金就能解决.jpg）这不是程序的问题，我无力解决，我只能保证我的程序是安全的。

**Comment by huzhiyuan1994** [comment]
但之前App.exe没这问题

**Comment by leck995** [comment]
> 但之前App.exe没这问题

你看1楼就会发现，此现象不论哪个版本都存在。自带的防护过于严格，对于非签名应用很容易弹报毒提示，最简单的办法，下个火绒就行。

**Comment by huzhiyuan1994** [comment]
以前没有的（或者是问一次选不每次都提醒就行），我之前用的还是[1.1.4](https://github.com/leck995/WutheringWavesTool/releases/tag/1.1.4)
现在新版本要不每次都问，就Internet选项-安全-自定义级别-加载应用程序和不安全文件-启用就行
![image](https://github.com/user-attachments/assets/6cf4438a-ce57-46c6-b212-56eab6296200)
PS：还在调用IE组件吗😅

**Comment by leck995** [comment]
我恢复了旧版本启动程序，按需选择好了
