### ISSUE TITLE
“我的角色”页面不显示详细信息

### ISSUE THREAD

**Issue by yihaoyu** [leck995/WutheringWavesTool#32]
系统WIN11, 显示语言英文，助手版本1.1.7，游戏服务器国服官服。
已导入库街区token，其他内容（如抽卡统计、签到等）都正常，但是“我的角色”中只显示了角色和等级，点进去没有其他内容，不知道为什么。
已尝试覆盖安装了font版本无果。1.1.7前的版本还没用过。
![image](https://github.com/user-attachments/assets/07b4a3d0-8891-4a73-99f6-6e3b48b6761a)
请问有大佬有什么排查手段么？谢谢！！

**Comment by leck995** [comment]
浏览器退出账号重新登陆，重新获取浏览器中的token

**Comment by yihaoyu** [comment]
可以使用了，感谢！请问TOKEN是否是不能和声骸小程序共用呀？一次只能用一处？

**Comment by leck995** [comment]
我不清楚小程序使用的是app token还是web token，不重新登陆token一般就可一直使用

**Comment by yihaoyu** [comment]
了解了，感谢解答！
