### ISSUE TITLE
更新相关问题

### ISSUE THREAD

**Issue by rosefatefans** [leck995/WutheringWavesTool#34]
大佬，覆盖安装是用新的压缩包解压后再复制到旧的文件夹里么，只有一个DATA文件夹保留，其他都替换了，这样就有个问题，还得重新添加主账号，之前的时常统计就没了

**Comment by leck995** [comment]
保证data，setting.json，sqlite.db与启动器在同一目录

**Comment by rosefatefans** [comment]
明白了，就是一直保留这三个，其他的后续更新直接覆盖就行了，是吧

**Comment by leck995** [comment]
是的，只要版本更新无特殊说明，即可直接覆盖
