### ISSUE TITLE
抽卡数据不存在 都设置好了

### ISSUE THREAD

**Issue by aaaol** [leck995/WutheringWavesTool#37]
![image](https://github.com/user-attachments/assets/b27e7c6e-db49-406e-8552-1c9df60a8186)
重新安装游戏无法解决
历史抽卡记录也打开了无数遍
游戏重启不下5次

**Comment by leck995** [comment]
暂不支持游戏与官方启动器分开的情况，如若继续使用，需要将其游戏本体放置在官方启动器文件夹中
