### ISSUE TITLE
无法进行构建

### ISSUE THREAD

**Issue by sweet-de-way** [leck995/WutheringWavesTool#4]
缺少cn.tealc.teafx而不能构建项目，我应该怎么获取这个库

**Comment by leck995** [comment]
疏忽了，前往[https://github.com/leck995/teafx](https://github.com/leck995/teafx)克隆，安装至本地maven仓库即可。项目有修改，保持最新版本再构建

**Comment by sweet-de-way** [comment]
非常感谢提供😖，我为项目添加了国际服的抽卡支持。希望能通过😣。

**Comment by leck995** [comment]
感谢PR
