### ISSUE TITLE
1.9版本打开后，转跳到设置界面会使所有界面空白

### ISSUE THREAD

**Issue by estella2012** [leck995/WutheringWavesTool#41]
覆盖安装到1.8版本，打开后右上角提示无法获取remote repository
![image](https://github.com/user-attachments/assets/c9704c87-8d74-432e-81d1-2bef6a1329c7)

以上界面看起来可以正常使用
![image](https://github.com/user-attachments/assets/468b0e4b-aecc-4d05-99e2-4086296acceb)

打开设置后显示白屏
![image](https://github.com/user-attachments/assets/7ab89e2c-810c-4ad7-8953-68917a4447fd)

之后所有界面均无法显示
![image](https://github.com/user-attachments/assets/72d3629f-0646-48eb-8512-0f41bcc4d6bd)

**Comment by leck995** [comment]
打开助手文件夹的setting.json，找到language将值en修改为zh_CN

**Comment by estella2012** [comment]
> 打开助手文件夹的setting.json，找到language将值en修改为zh_CN

谢谢大佬我刚改！
