### ISSUE TITLE
语言存在无法正确识别地域的问题

### ISSUE THREAD

**Issue by Kasofficial07** [leck995/WutheringWavesTool#42]
![image](https://github.com/user-attachments/assets/daa8dd1c-8ce5-4bf3-ae0e-d551fc3748e9)
1.1.8這裡是正常的

**Comment by Kasofficial07** [comment]
已找到原因，電腦預設英文，修改setting.json裡的language為zh_CN

**Comment by leck995** [comment]
是的，1.1.9添加了english的支持，但目前看来好像有些问题，非覆盖重新安装会出现该现象吗？

**Comment by Kasofficial07** [comment]
@leck995 
我是第一次使用，就是直接裝的1.1.9
