### ISSUE TITLE
在自定义里面定义了wwmi的启动（鸣潮mod）无法启动

### ISSUE THREAD

**Issue by AsukaSoryu0** [leck995/WutheringWavesTool#47]
在自定义里面定义了wwmi的启动（鸣潮mod）无法启动

**Comment by AsukaSoryu0** [comment]
The Loader is not configured correctly
![1](https://github.com/user-attachments/assets/5211597a-a266-4bff-b582-52f483dee4c5)

**Comment by AsukaSoryu0** [comment]
我用jasm的自定义启动wwmi是没问题的，不知道发生了什么。

**Comment by leck995** [comment]
助手本质只是启动其他exe程序，没有其他多余的操作。事实上，图片上已经提示你缺少dll与ini文件，请自行检查其文件是否存在于需要的地方。当然，你也可以尝试关闭助手的高级启动，以默认方式启动。
