### ISSUE TITLE
请问为什么抽卡记录无法读取

### ISSUE THREAD

**Issue by pikkooo** [leck995/WutheringWavesTool#56]
看了之前的Issues也确保了官方启动器和游戏本体在同一目录下，打开界面无角色获取也显示无法获取，已打开历史界面
![Snipaste_2024-11-16_15-11-17](https://github.com/user-attachments/assets/bd884b96-f12b-4169-94a3-dcbce37c2b0d)
![Snipaste_2024-11-16_15-11-37](https://github.com/user-attachments/assets/1c16a86f-2727-4830-ac19-05a196f2e4b3)

**Comment by leck995** [comment]
https://wave.tealc.fun/#/start

**Comment by RedChuak** [comment]
我是没有这个 无法获取抽卡数据链接的提示 就只有 一个正在获取数据的提示，提示没了就没反应了，没出记录也没报错。文档的解决方法都试过了，没有作用。不知道有没有解决办法。其他功能都可以正常使用。唯独抽卡分析无反应。
![image](https://github.com/user-attachments/assets/60ee19d5-cc8a-46e6-9f16-a29c9e6089f3)

**Comment by RedChuak** [comment]
> https://wave.tealc.fun/#/start

这个都已经试过了，没有作用

**Comment by leck995** [comment]
> 我是没有这个 无法获取抽卡数据链接的提示 就只有 一个正在获取数据的提示，提示没了就没反应了，没出记录也没报错。文档的解决方法都试过了，没有作用。不知道有没有解决办法。其他功能都可以正常使用。唯独抽卡分析无反应。 ![image](https://private-user-images.githubusercontent.com/76555967/386842116-60ee19d5-cc8a-46e6-9f16-a29c9e6089f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NTc5MDMsIm5iZiI6MTczMTc1NzYwMywicGF0aCI6Ii83NjU1NTk2Ny8zODY4NDIxMTYtNjBlZTE5ZDUtY2M4YS00NmU2LTlmMTYtYTI5YzllNjA4OWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDExNDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMGNhNTY2OGUyMWFlYTk5YjRjN2QyZDExZjE0MGY2MTZmNGFiNmE4YjI3NGZhYWRlYjY0NWQ4YTBlNzE3ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.foeZGG8swCa-N99wLTQAmU2I8XnL64TA1m1EqEGnZc4)         
加群私聊我

**Comment by Yanshao-ria** [comment]
> https://wave.tealc.fun/#/start

和题主一样的情况，这里的也尝试过了没有作用

**Comment by leck995** [comment]
> > https://wave.tealc.fun/#/start
> 
> 和题主一样的情况，这里的也尝试过了没有作用

请仔细按照要求检查并重试，若仍无法解决联系我。助手众多用户，抽卡分析所遇到的所有情况包含在文档内，基本不存在其他问题。

**Comment by ZeronoFreya** [comment]
你用了引擎优化了吗？是的话把以下内容删掉再试试

```
[Core.Log]
global=none
```

或许开发者可以自动启用禁用log，禁用log可能会提升一点性能？
