### ISSUE TITLE
获取不到抽卡数据

### ISSUE THREAD

**Issue by hukuhn-code** [leck995/WutheringWavesTool#57]
抽卡页面打开了获取不到数据,重启也没用. 其他的签到倒是能用
![Snipaste_2024-11-18_23-08-25](https://github.com/user-attachments/assets/716c3449-813a-4185-acd3-81c171a44384)

**Comment by ZeronoFreya** [comment]
你用了引擎优化了吗？是的话把以下内容删掉再试试

```
[Core.Log]
global=none
```

**Comment by leck995** [comment]
#56 重复
