### ISSUE TITLE
希望添加多端保存支持

### ISSUE THREAD

**Issue by Dreamry2C** [leck995/WutheringWavesTool#58]
我发现选定游戏位置后切换图片上这3个选项位置都一致。

![image](https://github.com/user-attachments/assets/7a67ec16-e05a-4a6f-9722-aca995dcf2bb)
我认为它的功能是每一个选项都有自己的游戏位置
![image](https://github.com/user-attachments/assets/b8146e9e-ea0a-47a6-8f62-543ef52b6295)
例如国际服文件位置是Wuthering Waves，国服是Wuthering Waves China   当我保存位置后点击切换国服国际服都是他们各自的位置而不是相同的。

> 如果可以的话希望像隔壁米哈游启动器实现快速切换国服国际服而不是下载两个服

**Comment by leck995** [comment]
助手不支持多游戏目录，未来大概也不会支持。至于多服下载与切换，尚处于开发中。
