### ISSUE TITLE
更新了之后反而出现了抽卡记录重复的问题

### ISSUE THREAD

**Issue by KrorainaCry** [leck995/WutheringWavesTool#62]
如题，今天更新之后常驻抽卡那里重复了两次，然后还计算错误了貌似

**Comment by leck995** [comment]
最新版1.2.0应该修复了这个错误。

助手拥有数据备份,[参考这里恢复正确的数据](https://wave.tealc.fun/#/func_card_analysis)，重新获取


如果是最新版，删除助手data文件夹内对应游戏uid的子文件，重新获取。
**如果是抽卡历史超过6个月，这个操作可能会导致以前数据丢失。你可以进群联系我，帮你恢复**

**Comment by KrorainaCry** [comment]
OK，我尝试替换了备份的数据，已经正常了，谢谢

**Comment by leck995** [comment]
v1.2.1之后可以通过导出插件，导出为excel后，删除excel中的重复数据，重新导入即可

**Comment by xiaoxingruo** [comment]
> v1.2.1之后可以通过导出插件，导出为excel后，删除excel中的重复数据，重新导入即可

最新版本依旧还有这个问题，他获取抽卡记录之后是把所有的抽卡数据写在后面，而不是识别上次的抽卡记录，将已经写入过的内容删除继续写，这个问题要怎么解决？不然我每次获取都会把以前的抽卡记录一起带上……

**Comment by leck995** [comment]
> > v1.2.1之后可以通过导出插件，导出为excel后，删除excel中的重复数据，重新导入即可
> 
> 最新版本依旧还有这个问题，他获取抽卡记录之后是把所有的抽卡数据写在后面，而不是识别上次的抽卡记录，将已经写入过的内容删除继续写，这个问题要怎么解决？不然我每次获取都会把以前的抽卡记录一起带上……

重新该问题的当天我已发布新版本修复，但很遗憾你并未及时更新。
旧版本的重复数据不会删除。
你有三种方法解决：
1. 如果备份是不重复的，恢复备份文件
2. 如果抽卡历史未超过6个月，直接删除用户抽卡历史重新获取
3. 导出为excel，手动删除重复项，然后导入覆盖

**Comment by xiaoxingruo** [comment]
> > > v1.2.1之后可以通过导出插件，导出为excel后，删除excel中的重复数据，重新导入即可
> > 
> > 
> > 最新版本依旧还有这个问题，他获取抽卡记录之后是把所有的抽卡数据写在后面，而不是识别上次的抽卡记录，将已经写入过的内容删除继续写，这个问题要怎么解决？不然我每次获取都会把以前的抽卡记录一起带上……
> 
> 重新该问题的当天我已发布新版本修复，但很遗憾你并未及时更新。 旧版本的重复数据不会删除。 你有三种方法解决：
> 
>     1. 如果备份是不重复的，恢复备份文件
> 
>     2. 如果抽卡历史未超过6个月，直接删除用户抽卡历史重新获取
> 
>     3. 导出为excel，手动删除重复项，然后导入覆盖

我现在恢复了以前的备份数据，但是我现在获取新的数据的时候依旧是重复的，也就是说他现在每次获取数据都是从这六个月最开始的写入，不会识别已经写入过的内容，而且新版本的排序和以前的还不一样，导出表格文件之后顺序是乱的，以前的记录在最下边，最新的记录写在最上边，弄的我都不知道怎么删除了

**Comment by leck995** [comment]
如果备份文件也是重复的，你可以参考选项2和3

**Comment by leck995** [comment]
> > > > v1.2.1之后可以通过导出插件，导出为excel后，删除excel中的重复数据，重新导入即可
> > > 
> > > 
> > > 最新版本依旧还有这个问题，他获取抽卡记录之后是把所有的抽卡数据写在后面，而不是识别上次的抽卡记录，将已经写入过的内容删除继续写，这个问题要怎么解决？不然我每次获取都会把以前的抽卡记录一起带上……
> > 
> > 
> > 重新该问题的当天我已发布新版本修复，但很遗憾你并未及时更新。 旧版本的重复数据不会删除。 你有三种方法解决：
> > ```
> > 1. 如果备份是不重复的，恢复备份文件
> > 
> > 2. 如果抽卡历史未超过6个月，直接删除用户抽卡历史重新获取
> > 
> > 3. 导出为excel，手动删除重复项，然后导入覆盖
> > ```
> 
> 我现在恢复了以前的备份数据，但是我现在获取新的数据的时候依旧是重复的，也就是说他现在每次获取数据都是从这六个月最开始的写入，不会识别已经写入过的内容，而且新版本的排序和以前的还不一样，导出表格文件之后顺序是乱的，以前的记录在最下边，最新的记录写在最上边，弄的我都不知道怎么删除了

如果备份文件也是重复的，你可以参考选项2和3

**Comment by xiaoxingruo** [comment]
> > > > > v1.2.1之后可以通过导出插件，导出为excel后，删除excel中的重复数据，重新导入即可
> > > > 
> > > > 
> > > > 最新版本依旧还有这个问题，他获取抽卡记录之后是把所有的抽卡数据写在后面，而不是识别上次的抽卡记录，将已经写入过的内容删除继续写，这个问题要怎么解决？不然我每次获取都会把以前的抽卡记录一起带上……
> > > 
> > > 
> > > 重新该问题的当天我已发布新版本修复，但很遗憾你并未及时更新。 旧版本的重复数据不会删除。 你有三种方法解决：
> > > ```
> > > 1. 如果备份是不重复的，恢复备份文件
> > > 
> > > 2. 如果抽卡历史未超过6个月，直接删除用户抽卡历史重新获取
> > > 
> > > 3. 导出为excel，手动删除重复项，然后导入覆盖
> > > ```
> > 
> > 
> > 我现在恢复了以前的备份数据，但是我现在获取新的数据的时候依旧是重复的，也就是说他现在每次获取数据都是从这六个月最开始的写入，不会识别已经写入过的内容，而且新版本的排序和以前的还不一样，导出表格文件之后顺序是乱的，以前的记录在最下边，最新的记录写在最上边，弄的我都不知道怎么删除了
> 
> 如果备份文件也是重复的，你可以参考选项2和3

备份的记录不是重复的，但是我现在如果获取新的抽卡记录那么新写入的记录就是重复的

**Comment by leck995** [comment]
> > > > > > v1.2.1之后可以通过导出插件，导出为excel后，删除excel中的重复数据，重新导入即可
> > > > > 
> > > > > 
> > > > > 最新版本依旧还有这个问题，他获取抽卡记录之后是把所有的抽卡数据写在后面，而不是识别上次的抽卡记录，将已经写入过的内容删除继续写，这个问题要怎么解决？不然我每次获取都会把以前的抽卡记录一起带上……
> > > > 
> > > > 
> > > > 重新该问题的当天我已发布新版本修复，但很遗憾你并未及时更新。 旧版本的重复数据不会删除。 你有三种方法解决：
> > > > ```
> > > > 1. 如果备份是不重复的，恢复备份文件
> > > > 
> > > > 2. 如果抽卡历史未超过6个月，直接删除用户抽卡历史重新获取
> > > > 
> > > > 3. 导出为excel，手动删除重复项，然后导入覆盖
> > > > ```
> > > 
> > > 
> > > 我现在恢复了以前的备份数据，但是我现在获取新的数据的时候依旧是重复的，也就是说他现在每次获取数据都是从这六个月最开始的写入，不会识别已经写入过的内容，而且新版本的排序和以前的还不一样，导出表格文件之后顺序是乱的，以前的记录在最下边，最新的记录写在最上边，弄的我都不知道怎么删除了
> > 
> > 
> > 如果备份文件也是重复的，你可以参考选项2和3
> 
> 备份的记录不是重复的，但是我现在如果获取新的抽卡记录那么新写入的记录就是重复的

应该不可能，我已经修复了，除非你用的是旧版本

**Comment by xiaoxingruo** [comment]
> > > > > > > v1.2.1之后可以通过导出插件，导出为excel后，删除excel中的重复数据，重新导入即可
> > > > > > 
> > > > > > 
> > > > > > 最新版本依旧还有这个问题，他获取抽卡记录之后是把所有的抽卡数据写在后面，而不是识别上次的抽卡记录，将已经写入过的内容删除继续写，这个问题要怎么解决？不然我每次获取都会把以前的抽卡记录一起带上……
> > > > > 
> > > > > 
> > > > > 重新该问题的当天我已发布新版本修复，但很遗憾你并未及时更新。 旧版本的重复数据不会删除。 你有三种方法解决：
> > > > > ```
> > > > > 1. 如果备份是不重复的，恢复备份文件
> > > > > 
> > > > > 2. 如果抽卡历史未超过6个月，直接删除用户抽卡历史重新获取
> > > > > 
> > > > > 3. 导出为excel，手动删除重复项，然后导入覆盖
> > > > > ```
> > > > 
> > > > 
> > > > 我现在恢复了以前的备份数据，但是我现在获取新的数据的时候依旧是重复的，也就是说他现在每次获取数据都是从这六个月最开始的写入，不会识别已经写入过的内容，而且新版本的排序和以前的还不一样，导出表格文件之后顺序是乱的，以前的记录在最下边，最新的记录写在最上边，弄的我都不知道怎么删除了
> > > 
> > > 
> > > 如果备份文件也是重复的，你可以参考选项2和3
> > 
> > 
> > 备份的记录不是重复的，但是我现在如果获取新的抽卡记录那么新写入的记录就是重复的
> 
> 应该不可能，我已经修复了，除非你用的是旧版本

难不成是我覆盖安装遗留下来的bug？我重新安装一下试试好了，不过我想要保留以前的抽卡记录，把以前抽卡记录那个文件复制到新的里面会不会出问题？

**Comment by leck995** [comment]
> > > > > > > > v1.2.1之后可以通过导出插件，导出为excel后，删除excel中的重复数据，重新导入即可
> > > > > > > 
> > > > > > > 
> > > > > > > 最新版本依旧还有这个问题，他获取抽卡记录之后是把所有的抽卡数据写在后面，而不是识别上次的抽卡记录，将已经写入过的内容删除继续写，这个问题要怎么解决？不然我每次获取都会把以前的抽卡记录一起带上……
> > > > > > 
> > > > > > 
> > > > > > 重新该问题的当天我已发布新版本修复，但很遗憾你并未及时更新。 旧版本的重复数据不会删除。 你有三种方法解决：
> > > > > > ```
> > > > > > 1. 如果备份是不重复的，恢复备份文件
> > > > > > 
> > > > > > 2. 如果抽卡历史未超过6个月，直接删除用户抽卡历史重新获取
> > > > > > 
> > > > > > 3. 导出为excel，手动删除重复项，然后导入覆盖
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 我现在恢复了以前的备份数据，但是我现在获取新的数据的时候依旧是重复的，也就是说他现在每次获取数据都是从这六个月最开始的写入，不会识别已经写入过的内容，而且新版本的排序和以前的还不一样，导出表格文件之后顺序是乱的，以前的记录在最下边，最新的记录写在最上边，弄的我都不知道怎么删除了
> > > > 
> > > > 
> > > > 如果备份文件也是重复的，你可以参考选项2和3
> > > 
> > > 
> > > 备份的记录不是重复的，但是我现在如果获取新的抽卡记录那么新写入的记录就是重复的
> > 
> > 
> > 应该不可能，我已经修复了，除非你用的是旧版本
> 
> 难不成是我覆盖安装遗留下来的bug？我重新安装一下试试好了，不过我想要保留以前的抽卡记录，把以前抽卡记录那个文件复制到新的里面会不会出问题？

不会

**Comment by xiaoxingruo** [comment]
> > > > > > > > > v1.2.1之后可以通过导出插件，导出为excel后，删除excel中的重复数据，重新导入即可
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 最新版本依旧还有这个问题，他获取抽卡记录之后是把所有的抽卡数据写在后面，而不是识别上次的抽卡记录，将已经写入过的内容删除继续写，这个问题要怎么解决？不然我每次获取都会把以前的抽卡记录一起带上……
> > > > > > > 
> > > > > > > 
> > > > > > > 重新该问题的当天我已发布新版本修复，但很遗憾你并未及时更新。 旧版本的重复数据不会删除。 你有三种方法解决：
> > > > > > > ```
> > > > > > > 1. 如果备份是不重复的，恢复备份文件
> > > > > > > 
> > > > > > > 2. 如果抽卡历史未超过6个月，直接删除用户抽卡历史重新获取
> > > > > > > 
> > > > > > > 3. 导出为excel，手动删除重复项，然后导入覆盖
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > 我现在恢复了以前的备份数据，但是我现在获取新的数据的时候依旧是重复的，也就是说他现在每次获取数据都是从这六个月最开始的写入，不会识别已经写入过的内容，而且新版本的排序和以前的还不一样，导出表格文件之后顺序是乱的，以前的记录在最下边，最新的记录写在最上边，弄的我都不知道怎么删除了
> > > > > 
> > > > > 
> > > > > 如果备份文件也是重复的，你可以参考选项2和3
> > > > 
> > > > 
> > > > 备份的记录不是重复的，但是我现在如果获取新的抽卡记录那么新写入的记录就是重复的
> > > 
> > > 
> > > 应该不可能，我已经修复了，除非你用的是旧版本
> > 
> > 
> > 难不成是我覆盖安装遗留下来的bug？我重新安装一下试试好了，不过我想要保留以前的抽卡记录，把以前抽卡记录那个文件复制到新的里面会不会出问题？
> 
> 不会

不行，就算是不覆盖再解压一份它也是直接把这六个月的抽卡记录直接写上去，就像我以前的记录不存在一样，和以前记录没办法共存了

**Comment by leck995** [comment]
> > > > > > > > > > v1.2.1之后可以通过导出插件，导出为excel后，删除excel中的重复数据，重新导入即可
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 最新版本依旧还有这个问题，他获取抽卡记录之后是把所有的抽卡数据写在后面，而不是识别上次的抽卡记录，将已经写入过的内容删除继续写，这个问题要怎么解决？不然我每次获取都会把以前的抽卡记录一起带上……
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 重新该问题的当天我已发布新版本修复，但很遗憾你并未及时更新。 旧版本的重复数据不会删除。 你有三种方法解决：
> > > > > > > > ```
> > > > > > > > 1. 如果备份是不重复的，恢复备份文件
> > > > > > > > 
> > > > > > > > 2. 如果抽卡历史未超过6个月，直接删除用户抽卡历史重新获取
> > > > > > > > 
> > > > > > > > 3. 导出为excel，手动删除重复项，然后导入覆盖
> > > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > 我现在恢复了以前的备份数据，但是我现在获取新的数据的时候依旧是重复的，也就是说他现在每次获取数据都是从这六个月最开始的写入，不会识别已经写入过的内容，而且新版本的排序和以前的还不一样，导出表格文件之后顺序是乱的，以前的记录在最下边，最新的记录写在最上边，弄的我都不知道怎么删除了
> > > > > > 
> > > > > > 
> > > > > > 如果备份文件也是重复的，你可以参考选项2和3
> > > > > 
> > > > > 
> > > > > 备份的记录不是重复的，但是我现在如果获取新的抽卡记录那么新写入的记录就是重复的
> > > > 
> > > > 
> > > > 应该不可能，我已经修复了，除非你用的是旧版本
> > > 
> > > 
> > > 难不成是我覆盖安装遗留下来的bug？我重新安装一下试试好了，不过我想要保留以前的抽卡记录，把以前抽卡记录那个文件复制到新的里面会不会出问题？
> > 
> > 
> > 不会
> 
> 不行，就算是不覆盖再解压一份它也是直接把这六个月的抽卡记录直接写上去，就像我以前的记录不存在一样，和以前记录没办法共存了

确认有问题加群私我
