### ISSUE TITLE
更新1.2.0后退出助手后游戏进程也会被立即结束。

### ISSUE THREAD

**Issue by kequeensuki** [leck995/WutheringWavesTool#63]
如题，看了下设置并没有发现退出助手后关闭游戏的设置，这应该是bug？
具体复现步骤：
    1.打开助手并启动游戏
    2.登录并成功进入游戏世界
    3.切换至助手鼠标点击右上角关闭图标并在弹出的提示框中选择退出
我试了3次都能稳定复现。

**Comment by leck995** [comment]
查看任务管理器，看看鸣潮进程是否在助手内，如果在助手内，关闭助手会导致游戏被杀。
正常情况下鸣潮和助手是单独的进程，但确实存在部分使用者下会出现上述情况，目前不清楚原因。

**Comment by kequeensuki** [comment]
> 查看任务管理器，看看鸣潮进程是否在助手内，如果在助手内，关闭助手会导致游戏被杀。 正常情况下鸣潮和助手是单独的进程，但确实存在部分使用者下会出现上述情况，目前不清楚原因。

找到问题了，当用户使用“WutheringWavesTool.exe”启动助手后，通过助手启动游戏，助手退出会导致游戏跟着退出，使用“App.exe"则没有此问题。
