### ISSUE TITLE
游戏时长成负数了

### ISSUE THREAD

**Issue by joinwuxiao** [leck995/WutheringWavesTool#64]
![image](https://github.com/user-attachments/assets/424e3840-b6df-47e1-9b3f-e57ed2c20735)
不知道怎么回事，更新之后玩了会，游戏时长成负数了

**Comment by leck995** [comment]
是的，有bug，旧版本因为有比较严重的bug，所以匆忙上了1.2.0，部分功能没有进行详细测试。你可以继续使用，后续我会处理这些错误数据。

**Comment by leck995** [comment]
已修复，下载最新版
