### ISSUE TITLE
1.2.0版本的游戏时长统计问题

### ISSUE THREAD

**Issue by ZaneGrilLcw** [leck995/WutheringWavesTool#66]
更新1.2.0版本后，游玩时长统计功能失效，想问一下这个是版本问题还是我的电脑的问题，如果是版本问题希望下一版尽快修复，如果是电脑问题麻烦告诉我调整的方法，heart~
![屏幕截图 2024-11-27 122410](https://github.com/user-attachments/assets/63422f17-da2f-4f7a-9906-e02f2ef55d63)

**Comment by leck995** [comment]
我真想顺着网线过去亲你两口，然后指着标题下的子菜单，告诉你，点点这里。
