### ISSUE TITLE
1.2.0 V2版本单日时长统计超24h

### ISSUE THREAD

**Issue by orange-inUSTC** [leck995/WutheringWavesTool#69]
更新之后没有负时间了，但之前错误统计的时长变得远超24h
![屏幕截图 2024-11-30 221317](https://github.com/user-attachments/assets/d724cc2e-8f83-40fe-840d-f5fd0e4e554c)
![屏幕截图 2024-11-30 221554](https://github.com/user-attachments/assets/1683ead8-68df-4f56-b0f9-55550e029caa)

**Comment by leck995** [comment]
已存在的错误数据暂时无法全部处理，后续会出时间调整功能。新的一天统计会完全正常

**Comment by orange-inUSTC** [comment]
![image](https://github.com/user-attachments/assets/333c2ae4-90c7-4ec9-bea5-09779fde3ed6)
抱歉打扰，新的记录依然不正常，每天第一次关游戏后刷新会显示时长为关闭游戏的时间点；后续再进行游戏时长会正常增加

**Comment by leck995** [comment]
>  每天第一次关游戏后刷新会显示时长为关闭游戏的时间点；后续再进行游戏时长会正常增加

 你是指第一次启动游戏，统计时长变成了退出游戏时的实际时间吗？

**Comment by orange-inUSTC** [comment]
对，而且游戏过程中是在正常记录时长的，退出游戏后刷新才变成了退出游戏时的实际时间

**Comment by leck995** [comment]
我使用最新发布版进行测试并没有出现上述问题，请确保是v2版本，如果再次出现上述问题，可以加群联系我
