### ISSUE TITLE
启动后整个ui文字显示错误

### ISSUE THREAD

**Issue by Realmajia** [leck995/WutheringWavesTool#7]
看上去像是文字编码的问题。如图。

![3M}T{QF~5D05HX6HW LGZW](https://github.com/user-attachments/assets/04c65fa5-1fab-4513-9b3a-99eb9f73932a)
![4ED)SH~ZXNFBAQ %7Y02$Q](https://github.com/user-attachments/assets/ab7fe362-c574-4dea-a673-2c8fc8b529bd)
![1BQRWXFP NOS73XDI4{26J6](https://github.com/user-attachments/assets/3b8f7ce6-4a47-4032-a75e-42dbb8bfa0b5)

**Comment by sweet-de-way** [comment]
可以提供，软件的运行环境吗。
看起来像是javafx指定的默认字体有问题。
也许，我们可以通过安装一个指定字体来解决。

**Comment by Realmajia** [comment]
系统就正常更新的win10 22H2 19045.4598。
然后就一些普通的游戏运行需要的windows runtime运行库。
再就是有一个应该没啥影响的anaconda3 2023.07-2。
找了找没找到这软件有log。貌似没办法提交啊。

**Comment by leck995** [comment]
1. 尝试使用 安装目录/bin/app.bat 启动程序；
2. 系统是否是精简系统，或者修改了字体？
诚如上面所言，我也怀疑是调用系统字体出了问题，程序为了尽量减少占用体积，所以并没有内置字体。
如果上述无法解决，我上传了一个内置字体的版本，你可以试试[下载带有font标志的压缩包](https://github.com/leck995/WutheringWavesTool/releases/tag/1.1.2)

**Comment by Realmajia** [comment]
1.无效
2.是一直正常更新的官方系统。使用带有字体的font包内app显示正常。

**Comment by Realmajia** [comment]
主界面正常。添加账号的二级页面问题依旧。
![Q5TWU3 8FB9(%RIHV0$JSW4](https://github.com/user-attachments/assets/b21bce1b-5a39-4a3a-9bf9-7ab9536afff4)

**Comment by leck995** [comment]
是的，字体的更换产生了影响；
子窗口存在不多，加上当前内置的字体与界面并不搭配，我需要寻找一款合适的字体，你可以暂时使用着，后续会进行更新，该子窗口正常文字如下。
![2024-07-14 18 59 39](https://github.com/user-attachments/assets/4207f563-808e-4511-915e-9544d8c366ee)

**Comment by leck995** [comment]
哦，对了，你也可以重新安装微软雅黑字体，这样应该也能解决问题

**Comment by Realmajia** [comment]
了解。感谢回答。顺便不方便找合适的字体的话建议能否提供一个自选字体的选项或者给个fonts文件夹下放自己字体适配的方案？

**Comment by leck995** [comment]
最新版发布，如果仍有问题，请上传安装目录下/log/client.log

**Comment by Realmajia** [comment]
![image](https://github.com/user-attachments/assets/8b835069-3794-4918-a561-9b48f2a33051)
下载了最新版，字体显示在主界面和二级菜单都是正常的。各功能都正常。玩家角色等级显示不全估计是4k显示器下dpi缩放相关的神秘因素造成的。当前使用已经完全ok了。感谢。
ps：如果想内置字体的话推荐试试苍耳个人免费商用的苍耳今楷、云黑，或者永久免费的仓耳渔阳体之类的字体。

**Comment by leck995** [comment]
该GUI对字体的兼容并不好，很多看起来不错的字体内置后会出现不少问题，如缺少粗体，严重发虚等情况，我刚刚看了下推荐的，很显然并不满足。

**Comment by Realmajia** [comment]
原来这gui有这个问题吗。那或许只能可以去试试选择字重更高的字体了。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: leck995 ***@***.***>
发送时间: Monday, July 15, 2024 8:45:33 PM
收件人: leck995/WutheringWavesTool ***@***.***>
抄送: Realmajia ***@***.***>; Author ***@***.***>
主题: Re: [leck995/WutheringWavesTool] 启动后整个ui文字显示错误 (Issue #7)


该GUI对字体的兼容并不好，很多看起来不错的字体内置后会出现不少问题，如缺少粗体，严重发虚等情况，我刚刚看了下推荐的，很显然并不满足。

―
