### ISSUE TITLE
退出助手时会同时结束游戏进程，能否改为设置项，可以设置退出助手时是否结束游戏进程

### ISSUE THREAD

**Issue by LiunianShuai** [leck995/WutheringWavesTool#72]
![image](https://github.com/user-attachments/assets/aefa90a5-18d6-4932-8ad5-2265d9972d2e)
我重启下助手，游戏给我整没了，太影响体验了，希望作者有空的时候可以看看，万分感谢！

**Comment by leck995** [comment]
参考 #63
