### ISSUE TITLE
重新打开应用会导致游戏路径消失

### ISSUE THREAD

**Issue by Arcadia7** [leck995/WutheringWavesTool#8]
![image](https://github.com/user-attachments/assets/2f18ab39-baae-4ece-a6cf-db53da9ba8f4)
同时我发现文件结构和上个版本相比 没有之前那个记录游戏路径的json文件了
![image](https://github.com/user-attachments/assets/0f92d486-ae21-4049-ba2b-e449cbd46a6e)
可能是这个原因导致的
我当前使用的是将1.1.2的文件覆盖到1.1.1版本更新的1.1.2

**Comment by leck995** [comment]
配置文件在每次程序退出是会进行创建与保存，可能是程序异常关闭时出现异常导致配置文件没有顺利保存。重新设置就可以了

**Comment by leck995** [comment]
已修复，下载最新版即可
